export const LOGIN_DATA = 'LOGIN_DATA'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'
export const SIGN_UP = 'SIGN_UP'
export const SINGNUP_ERROR = 'SINGNUP_ERROR'
export const GOOGLE_SIGNUP_SUCCESS = 'GOOGLE_SIGNUP_SUCCESS'
export const GOOGLE_SIGNUP_ERROR = 'GOOGLE_SIGNUP_ERROR'
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_ERROR = 'GOOGLE_LOGIN_ERROR'
export const FORGET_PASSWORD = 'FORGET_PASSWORD'
export const NEW_PASSWORD = 'NEW_PASSWORD'
export const PASSWORD_ERROR = 'PASSWORD_ERROR'
export const JOBS_LIST = 'JOBS_LIST'

export const ADMIN_LOGIN = 'ADMIN_LOGIN'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR'

export const LOG_OUT = 'LOG_OUT'

export const COMPANIES_LIST = 'COMPANIES_LIST'
export const SWITCH_ACTIVE = 'SWITCH_ACTIVE'
export const SWITCH_INACTIVE = 'SWITCH_INACTIVE'
export const JOBS_CATEGORY_LIST = 'JOBS_CATEGORY_LIST'

export const PROFILE_DATA = 'PROFILE_DATA'
export const BENEFITS_DATA = 'BENEFITS_DATA'
export const JOB_TYPE = 'JOB_TYPE'
export const COMPANY_SIZE = 'COMPANY_SIZE'
export const DEV_TYPE = 'DEV_TYPE'
export const NEWPASSWORD_ERROR = 'NEWPASSWORD_ERROR'
export const CERT_TYPE = 'CERT_TYPE'
export const TRADE_UPDATE = 'TRADE_UPDATE'
export const GENERAL_UPDATE = 'GENERAL_UPDATE'
export const WORK_UPDATE = 'WORK_UPDATE'
export const CERT_UPDATE = 'CERT_UPDATE'
export const WORKPREF_UPDATE = 'WORKPREF_UPDATE'
export const PROFILE_INFO = 'PROFILE_INFO'
export const PROFILE_SINGLE_INFO = 'PROFILE_SINGLE_INFO'
export const WORKER_PROFILE_DETAIL = 'WORKER_PROFILE_DETAIL'
export const PROFILE_INFO_ERROR = 'PROFILE_INFO_ERROR'
export const COUNTRY_LIST = 'COUNTRY_LIST'

export const JOBS_CATEGORY_SKILLS = 'JOBS_CATEGORY_SKILLS'
export const GET_JOB_CATEGORIES = 'GET_JOB_CATEGORIES'
export const GET_JOB_CATEGORIES_SUCCESS = 'GET_JOB_CATEGORIES_SUCCESS'
export const GET_JOB_CATEGORIES_ERROR = 'GET_JOB_CATEGORIES_ERROR'

export const GET_JOBS = 'GET_JOBS'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'
export const GET_JOBS_ERROR = 'GET_JOBS_ERROR'

export const FILTER_JOBS = 'FILTER_JOBS'
export const FILTER_JOBS_SUCCESS = 'FILTER_JOBS_SUCCESS'
export const FILTER_JOBS_ERROR = 'FILTER_JOBS_ERROR'

export const APPLY_JOB = 'APPLY_JOB'
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS'
export const APPLY_JOB_ERROR = 'APPLY_JOB_ERROR'

export const ADD_REMOVE_FAVOURITE_JOB = 'ADD_REMOVE_FAVOURITE_JOB'
export const ADD_REMOVE_FAVOURITE_JOB_SUCCESS =
	'ADD_REMOVE_FAVOURITE_JOB_SUCCESS'
export const ADD_REMOVE_FAVOURITE_JOB_ERROR = 'ADD_REMOVE_FAVOURITE_JOB_ERROR'

export const GET_SAVED_JOBS = 'GET_SAVED_JOBS'
export const GET_SAVED_JOBS_SUCCESS = 'GET_SAVED_JOBS_SUCCESS'
export const GET_SAVED_JOBS_ERROR = 'GET_SAVED_JOBS_ERROR'

export const LOCATION_LIST = 'LOCATION_LIST'
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS'
export const LOCATION_LIST_ERROR = 'LOCATION_LIST_ERROR'

export const CERTIFICATE_LIST = 'CERTIFICATE_LIST'
export const CERTIFICATE_LIST_SUCCESS = 'CERTIFICATE_LIST_SUCCESS'
export const CERTIFICATE_LIST_ERROR = 'CERTIFICATE_LIST_ERROR'

export const BENEFIT_LIST = 'BENEFIT_LIST'
export const BENEFIT_LIST_SUCCESS = 'BENEFIT_LIST_SUCCESS'
export const BENEFIT_LIST_ERROR = 'BENEFIT_LIST_ERROR'

export const CATEGORY_LIST = 'CATEGORY_LIST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_ERROR = 'CATEGORY_LIST_ERROR'
export const SAVE_JOB = 'SAVE_JOB'
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCCESS'
export const SAVE_JOB_ERROR = 'SAVE_JOB_ERROR'

export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS'
export const GET_COMPANIES_ERROR = 'GET_COMPANIES_ERROR'

export const SAVE_UNSAVE_COMPANY = 'SAVE_UNSAVE_COMPANY'
export const SAVE_UNSAVE_COMPANY_SUCCESS = 'SAVE_UNSAVE_COMPANY_SUCCESS'
export const SAVE_UNSAVE_COMPANY_ERROR = 'SAVE_UNSAVE_COMPANY_ERROR'

export const FILTER_COMPANIES = 'FILTER_COMPANIES'
export const FILTER_COMPANIES_SUCCESS = 'FILTER_COMPANIES_SUCCESS'
export const FILTER_COMPANIES_ERROR = 'FILTER_COMPANIES_ERROR'

export const GET_TOP_COMPANIES = 'GET_TOP_COMPANIES'
export const GET_TOP_COMPANIES_SUCCESS = 'GET_TOP_COMPANIES_SUCCESS'
export const GET_TOP_COMPANIES_ERROR = 'GET_TOP_COMPANIES_ERROR'

export const JOB_TYPE_LIST = 'JOB_TYPE_LIST'
export const JOB_TYPE_LIST_SUCCESS = 'JOB_TYPE_LIST_SUCCESS'
export const JOB_TYPE_LIST_ERROR = 'JOB_TYPE_LIST_ERROR'

export const JOB_ROLE_LIST = 'JOB_ROLE_LIST'
export const JOB_ROLE_LIST_SUCCESS = 'JOB_ROLE_LIST_SUCCESS'
export const JOB_ROLE_LIST_ERROR = 'JOB_ROLE_LIST_ERROR'

export const JOB_POST = 'JOB_POST'
export const JOB_POST_SUCCESS = 'JOB_POST_SUCCESS'
export const JOB_POST_ERROR = 'JOB_POST_ERROR'
export const CLEAR_JOB_POST = 'CLEAR_JOB_POST'

export const EMPLOYER_DASHBOARD_MESSAGE_LIST = 'EMPLOYER_DASHBOARD_MESSAGE_LIST'
export const EMPLOYER_DASHBOARD_MESSAGE_LIST_SUCCESS =
	'EMPLOYER_DASHBOARD_MESSAGE_LIST_SUCCESS'
export const EMPLOYER_DASHBOARD_MESSAGE_LIST_ERROR =
	'EMPLOYER_DASHBOARD_MESSAGE_LIST_ERROR'

export const EMPLOYER_DASHBOARD_NOTIFICATION_LIST =
	'EMPLOYER_DASHBOARD_NOTIFICATION_LIST'
export const EMPLOYER_DASHBOARD_NOTIFICATION_LIST_SUCCESS =
	'EMPLOYER_DASHBOARD_NOTIFICATION_LIST_SUCCESS'
export const EMPLOYER_DASHBOARD_NOTIFICATION_LIST_ERROR =
	'EMPLOYER_DASHBOARD_NOTIFICATION_LIST_ERROR'

export const EMPLOYER_DASHBOARD_JOB_LIST = 'EMPLOYER_DASHBOARD_JOB_LIST'
export const EMPLOYER_DASHBOARD_JOB_LIST_SUCCESS =
	'EMPLOYER_DASHBOARD_JOB_LIST_SUCCESS'
export const EMPLOYER_DASHBOARD_JOB_LIST_ERROR =
	'EMPLOYER_DASHBOARD_JOB_LIST_ERROR'

export const EMPLOYER_JOB_LIST = 'EMPLOYER_JOB_LIST'
export const EMPLOYER_JOB_LIST_SUCCESS = 'EMPLOYER_JOB_LIST_SUCCESS'
export const EMPLOYER_JOB_LIST_ERROR = 'EMPLOYER_JOB_LIST_ERROR'

export const EMPLOYER_PUBLISHED_JOB_LIST = 'EMPLOYER_PUBLISHED_JOB_LIST'
export const EMPLOYER_PUBLISHED_JOB_LIST_SUCCESS =
	'EMPLOYER_PUBLISHED_JOB_LIST_SUCCESS'
export const EMPLOYER_PUBLISHED_JOB_LIST_ERROR =
	'EMPLOYER_PUBLISHED_JOB_LIST_ERROR'

export const EMPLOYER_DRAFT_JOB_LIST = 'EMPLOYER_DRAFT_JOB_LIST'
export const EMPLOYER_DRAFT_JOB_LIST_SUCCESS = 'EMPLOYER_DRAFT_JOB_LIST_SUCCESS'
export const EMPLOYER_DRAFT_JOB_LIST_ERROR = 'EMPLOYER_DRAFT_JOB_LIST_ERROR'

export const EMPLOYER_EXPIRED_JOB_LIST = 'EMPLOYER_EXPIRED_JOB_LIST'
export const EMPLOYER_EXPIRED_JOB_LIST_SUCCESS =
	'EMPLOYER_EXPIRED_JOB_LIST_SUCCESS'
export const EMPLOYER_EXPIRED_JOB_LIST_ERROR = 'EMPLOYER_EXPIRED_JOB_LIST_ERROR'

export const GET_JOB_DESCRIPTION = 'GET_JOB_DESCRIPTION '
export const GET_JOB_DESCRIPTION_SUCCESS = 'GET_JOB_DESCRIPTION_SUCCESS '
export const GET_JOB_DESCRIPTION_ERROR = 'GET_JOB_DESCRIPTION_ERROR '

export const GET_COMPANY_SIZE = 'GET_COMPANY_SIZE'
export const GET_COMPANY_SIZE_SUCCESS = 'GET_COMPANY_SIZE_SUCCESS'
export const GET_COMPANY_SIZE_ERROR = 'GET_COMPANY_SIZE_ERROR'

export const EMPLOYER_APPLIED_JOB_LIST = 'EMPLOYER_APPLIED_JOB_LIST'
export const EMPLOYER_APPLIED_JOB_LIST_SUCCESS =
	'EMPLOYER_APPLIED_JOB_LIST_SUCCESS'
export const EMPLOYER_APPLIED_JOB_LIST_ERROR = 'EMPLOYER_APPLIED_JOB_LIST_ERROR'

export const EMPLOYER_APPLIED_JOB_CANDIDATE_LIST =
	'EMPLOYER_APPLIED_JOB_CANDIDATE_LIST'
export const EMPLOYER_APPLIED_JOB_CANDIDATE_LIST_SUCCESS =
	'EMPLOYER_APPLIED_JOB_CANDIDATE_LIST_SUCCESS'
export const EMPLOYER_APPLIED_JOB_CANDIDATE_LIST_ERROR =
	'EMPLOYER_APPLIED_JOB_CANDIDATE_LIST_ERROR'

export const EMPLOYER_APPLIED_JOB_INTERVIEW_CANDIDATE_LIST =
	'EMPLOYER_APPLIED_JOB_INTERVIEW_CANDIDATE_LIST'
export const EMPLOYER_APPLIED_JOB_INTERVIEW_CANDIDATE_LIST_SUCCESS =
	'EMPLOYER_APPLIED_JOB_INTERVIEW_CANDIDATE_LIST_SUCCESS'
export const EMPLOYER_APPLIED_JOB_INTERVIEW_CANDIDATE_LIST_ERROR =
	'EMPLOYER_APPLIED_JOB_INTERVIEW_CANDIDATE_LIST_ERROR'

export const EMPLOYER_UPDATE_PROFILE = 'EMPLOYER_UPDATE_PROFILE'
export const EMPLOYER_UPDATE_PROFILE_SUCCESS = 'EMPLOYER_UPDATE_PROFILE_SUCCESS'
export const EMPLOYER_UPDATE_PROFILE_ERROR = 'EMPLOYER_UPDATE_PROFILE_ERROR'
export const CLEAR_EMPLOYER_UPDATE_PROFILE = 'CLEAR_EMPLOYER_UPDATE_PROFILE'
//User List Action Types

export const GET_USER_SUGGESTION = 'GET_USER_SUGGESTION'
export const GET_USER_SUGGESTION_SUCCESS = 'GET_USER_SUGGESTION_SUCCESS'
export const GET_USER_SUGGESTION_ERROR = 'GET_USER_SUGGESTION_ERROR'

//Recommended Jobs action types

export const GET_RECOMMENDED_JOBS = 'GET_RECOMMENDED_JOBS'
export const GET_RECOMMENDED_JOBS_SUCCESS = 'GET_RECOMMENDED_JOBS_SUCCESS'
export const GET_RECOMMENDED_JOBS_ERROR = 'GET_RECOMMENDED_JOBS_ERROR'

//Job Application Status Action Types

export const GET_JOB_APPLICATIONS = 'GET_USER_APPLICATIONS'
export const GET_JOB_APPLICATIONS_SUCCESS = 'GET_USER_APPLICATIONS_SUCCESS'
export const GET_JOB_APPLICATIONS_ERROR = 'GET_USER_APPLICATIONS_ERROR'

//Worker Dashboard Data Count

export const WORKER_DASHBOARD_DATA_COUNT = 'WORKER_DASHBOARD_DATA_COUNT'
export const WORKER_DASHBOARD_DATA_COUNT_SUCCESS =
	'WORKER_DASHBOARD_DATA_COUNT_SUCCESS'
export const WORKER_DASHBOARD_DATA_COUNT_ERROR =
	'WORKER_DASHBOARD_DATA_COUNT_ERROR'

export const GET_COMPANY_JOBS_LIST = 'GET_COMPANY_JOBS_LIST'
export const GET_COMPANY_JOBS_LIST_SUCCESS = 'GET_COMPANY_JOBS_LIST_SUCCESS'
export const GET_COMPANY_JOBS_LIST_ERROR = 'GET_COMPANY_JOBS_LIST_ERROR'
export const EMPLOYER_TOGGLE_JOB_STATUS = 'EMPLOYER_TOGGLE_JOB_STATUS'
export const EMPLOYER_TOGGLE_JOB_STATUS_SUCCESS =
	'EMPLOYER_TOGGLE_JOB_STATUS_SUCCESS'
export const EMPLOYER_TOGGLE_JOB_STATUS_ERROR =
	'EMPLOYER_TOGGLE_JOB_STATUS_ERROR'

export const EMPLOYER_APPLIED_JOB_CANDIDATE_PHASE_CHANGE =
	'EMPLOYER_APPLIED_JOB_CANDIDATE_PHASE_CHANGE'
export const EMPLOYER_APPLIED_JOB_CANDIDATE_PHASE_CHANGE_SUCCESS =
	'EMPLOYER_APPLIED_JOB_CANDIDATE_PHASE_CHANGE_SUCCESS'
export const EMPLOYER_APPLIED_JOB_CANDIDATE_PHASE_CHANGE_ERROR =
	'EMPLOYER_APPLIED_JOB_INTERVIEW_CANDIDATE_LIST_ERROR'

export const EMPLOYER_JOB_DETAIL = 'EMPLOYER_JOB_DETAIL'
export const EMPLOYER_JOB_DETAIL_SUCCESS = 'EMPLOYER_JOB_DETAIL_SUCCESS'
export const EMPLOYER_JOB_DETAIL_ERROR = 'EMPLOYER_JOB_DETAIL_ERROR'

export const EMPLOYER_UPDATE_COMPANY_PROFILE = 'EMPLOYER_UPDATE_COMPANY_PROFILE'
export const EMPLOYER_UPDATE_COMPANY_PROFILE_SUCCESS =
	'EMPLOYER_UPDATE_COMPANY_PROFILE_SUCCESS'
export const EMPLOYER_UPDATE_COMPANY_PROFILE_ERROR =
	'EMPLOYER_UPDATE_COMPANY_PROFILE_ERROR'
export const CLEAR_EMPLOYER_UPDATE_COMPANY_PROFILE =
	'CLEAR_EMPLOYER_UPDATE_COMPANY_PROFILE'

export const EMPLOYER_PROFILE_DETAIL = 'EMPLOYER_PROFILE_DETAIL'
export const EMPLOYER_PROFILE_DETAIL_SUCCESS = 'EMPLOYER_PROFILE_DETAIL_SUCCESS'
export const EMPLOYER_PROFILE_DETAIL_ERROR =
	'EMPLOYER_UPDATE_COMPANY_PROFILE_ERROR'

export const EMPLOYER_INVITE_CANDIDATE_LIST = 'EMPLOYER_INVITE_CANDIDATE_LIST'
export const EMPLOYER_INVITE_CANDIDATE_LIST_SUCCESS =
	'EMPLOYER_INVITE_CANDIDATE_LIST_SUCCESS'
export const EMPLOYER_INVITE_CANDIDATE_LIST_ERROR =
	'EMPLOYER_APPLIED_JOB_CANDIDATE_LIST_ERROR'

export const EMPLOYER_DASHBOARD_DATA_COUNT = 'EMPLOYER_DASHBOARD_DATA_COUNT'
export const EMPLOYER_DASHBOARD_DATA_COUNT_SUCCESS =
	'EMPLOYER_DASHBOARD_DATA_COUNT_SUCCESS'
export const EMPLOYER_DASHBOARD_DATA_COUNT_ERROR =
	'EMPLOYER_DASHBOARD_NOTIFICATION_LIST_ERROR'

export const EMPLOYER_SEARCH = 'EMPLOYER_SEARCH'
export const EMPLOYER_SEARCH_SUCCESS = 'EMPLOYER_SEARCH_SUCCESS'
export const EMPLOYER_SEARCH_ERROR = 'EMPLOYER_SEARCH_ERROR'

export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION'
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS'
export const GET_SUBSCRIPTION_ERROR = 'GET_SUBSCRIPTION_ERROR'

export const ADMIN_MESSAGE_DELETE = 'ADMIN_MESSAGE_DELETE'
export const ADMIN_MESSAGE_DELETE_SUCESS = 'ADMIN_MESSAGE_DELETE_SUCESS'
export const ADMIN_MESSAGE_DELETE_ERROR = 'ADMIN_MESSAGE_DELETE_ERROR'

export const ADMIN_TRADEPERSON = 'ADMIN_TRADEPERSON'
export const ADMIN_TRADEPERSON_SUCCESS = 'ADMIN_TRADEPERSON_SUCCESS'
export const ADMIN_TRADEPERSON_ERROR = 'ADMIN_TRADEPERSON_ERROR'

export const ADMIN_COMPANY = 'ADMIN_COMPANY'
export const ADMIN_COMPANY_SUCCESS = 'ADMIN_COMPANY_SUCCESS'
export const ADMIN_COMPANY_ERROR = 'ADMIN_COMPANY_ERROR'

export const ADMIN_REGISTER = 'ADMIN_REGISTER'
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS'
export const ADMIN_REGISTER_ERROR = 'ADMIN_REGISTER_ERROR'

export const ADMIN_RESOLVED = 'ADMIN_RESOLVED'
export const ADMIN_RESOLVED_SUCCESS = 'ADMIN_RESOLVED_SUCCESS'
export const ADMIN_RESOLVED_ERROR = 'ADMIN_RESOLVED_ERROR'

export const ADMIN_DATACOUNT = 'ADMIN_DATACOUNT'
export const ADMIN_DATACOUNT_SUCCESS = 'ADMIN_DATACOUNT_SUCCESS'
export const ADMIN_DATACOUNT_ERROR = 'ADMIN_DATACOUNT_ERROR'
export const EMPLOYER_GET_TEAM_MEMBER = 'EMPLOYER_GET_TEAM_MEMBER'
export const EMPLOYER_GET_TEAM_MEMBER_SUCCESS =
	'EMPLOYER_GET_TEAM_MEMBER_SUCCESS'
export const EMPLOYER_GET_TEAM_MEMBER_ERROR = 'EMPLOYER_GET_TEAM_MEMBER_ERROR'

export const EMPLOYER_GET_TEAM_MEMBER_DETAIL = 'EMPLOYER_GET_TEAM_MEMBER_DETAIL'
export const EMPLOYER_GET_TEAM_MEMBER_DETAIL_SUCCESS =
	'EMPLOYER_GET_TEAM_MEMBER_DETAIL_SUCCESS'
export const EMPLOYER_GET_TEAM_MEMBER_DETAIL_ERROR =
	'EMPLOYER_GET_TEAM_MEMBER_DETAIL_ERROR'

export const EMPLOYER_ADD_TEAM_MEMBER = 'EMPLOYER_ADD_TEAM_MEMBER'
export const EMPLOYER_ADD_TEAM_MEMBER_SUCCESS =
	'EMPLOYER_ADD_TEAM_MEMBER_SUCCESS'
export const EMPLOYER_ADD_TEAM_MEMBER_ERROR = 'EMPLOYER_ADD_TEAM_MEMBER_ERROR'
export const EMPLOYER_ADD_TEAM_MEMBER_CLEAR = 'EMPLOYER_ADD_TEAM_MEMBER_CLEAR'

export const EMPLOYER_LIKE_CANDIDATE_PROFILE = 'EMPLOYER_LIKE_CANDIDATE_PROFILE'
export const EMPLOYER_LIKE_CANDIDATE_PROFILE_SUCCESS =
	'EMPLOYER_LIKE_CANDIDATE_PROFILE_SUCCESS'
export const EMPLOYER_LIKE_CANDIDATE_PROFILE_ERROR =
	'EMPLOYER_LIKE_CANDIDATE_PROFILE_ERROR'

export const EMPLOYER_UNLIKE_CANDIDATE_PROFILE =
	'EMPLOYER_UNLIKE_CANDIDATE_PROFILE'
export const EMPLOYER_UNLIKE_CANDIDATE_PROFILE_SUCCESS =
	'EMPLOYER_UNLIKE_CANDIDATE_PROFILE_SUCCESS'
export const EMPLOYER_UNLIKE_CANDIDATE_PROFILE_ERROR =
	'EMPLOYER_UNLIKE_CANDIDATE_PROFILE_ERROR'

export const SUBSCRIBE_SUBSCRIPTION = 'SUBSCRIBE_SUBSCRIPTION'
export const SUBSCRIBE_SUBSCRIPTION_SUCCESS = 'SUBSCRIBE_SUBSCRIPTION_SUCCESS'
export const SUBSCRIBE_SUBSCRIPTION_ERROR = 'SUBSCRIBE_SUBSCRIPTION_ERROR'
export const SUBSCRIBE_SUBSCRIPTION_CLEAR = 'SUBSCRIBE_SUBSCRIPTION_CLEAR'
