export const GET_USERS_SUGGESTION = 'GET_USER_SUGGESTION'
export const GET_USERS_SUGGESTION_SUCCESS = 'GET_USER_SUGGESTION_SUCCESS'
export const GET_USERS_SUGGESTION_ERROR = 'GET_USER_SUGGESTION_ERROR'

export const GET_COMPANIES_TO_FOLLOW = 'GET_COMPANIES_TO_FOLLOW'
export const GET_COMPANIES_TO_FOLLOW_SUCCESS = 'GET_COMPANIES_TO_FOLLOW_SUCCESS'
export const GET_COMPANIES_TO_FOLLOW_ERROR = 'GET_COMPANIES_TO_FOLLOW_ERROR'

export const GET_USER_INVITATIONS = 'GET_USER_INVITATIONS'
export const GET_USER_INVITATIONS_SUCCESS = 'GET_USER_INVITATIONS_SUCCESS'
export const GET_USER_INVITATIONS_ERROR = 'GET_USER_INVITATIONS_ERROR'

export const DASHBOARD_ADD_POST = 'DASHBOARD_ADD_POST'
export const DASHBOARD_ADD_POST_SUCCESS = 'DASHBOARD_ADD_POST_SUCCESS'
export const DASHBOARD_ADD_POST_ERROR = 'DASHBOARD_ADD_POST_ERROR'

export const DASHBOARD_GET_POSTS = 'DASHBOARD_GET_POSTS'
export const DASHBOARD_GET_POSTS_SUCCESS = 'DASHBOARD_GET_POSTS_SUCCESS'
export const DASHBOARD_GET_POSTS_ERROR = 'DASHBOARD_GET_POSTS_ERROR'

export const DASHBOARD_DELETE_POST = 'DASHBOARD_DELETE_POST'
export const DASHBOARD_DELETE_POST_SUCCESS = 'DASHBOARD_DELETE_POST_SUCCESS'
export const DASHBOARD_DELETE_POST_ERROR = 'DASHBOARD_DELETE_POST_ERROR'

export const DASHBOARD_LIKE_UNLIKE_POST = 'DASHBOARD_LIKE_UNLIKE_POST'
export const DASHBOARD_LIKE_UNLIKE_POST_SUCCESS =
	'DASHBOARD_LIKE_UNLIKE_POST_SUCCESS'
export const DASHBOARD_LIKE_UNLIKE_POST_ERROR =
	'DASHBOARD_LIKE_UNLIKE_POST_ERROR'

export const DASHBOARD_POST_COMMENT = 'DASHBOARD_POST_COMMENT'
export const DASHBOARD_POST_COMMENT_SUCCESS = 'DASHBOARD_POST_COMMENT_SUCCESS'
export const DASHBOARD_POST_COMMENT_ERROR = 'DASHBOARD_POST_COMMENT_ERROR'

export const CANDIDATE_GET_MESSAGES = 'CANDIDATE_GET_MESSAGES'
export const CANDIDATE_GET_MESSAGES_SUCCESS = 'CANDIDATE_GET_MESSAGES_SUCCESS'
export const CANDIDATE_GET_MESSAGES_ERROR = 'CANDIDATE_GET_MESSAGES_ERROR'

export const CANDIDATE_GET_CONVERSATION = 'CANDIDATE_GET_CONVERSATION'
export const CANDIDATE_GET_CONVERSATION_SUCCESS =
	'CANDIDATE_GET_CONVERSATION_SUCCESS'
export const CANDIDATE_GET_CONVERSATION_ERROR =
	'CANDIDATE_GET_CONVERSATION_ERROR'

export const CANDIDATE_SEND_MESSAGE = 'CANDIDATE_SEND_MESSAGE'
export const CANDIDATE_SEND_MESSAGE_SUCCESS = 'CANDIDATE_SEND_MESSAGE_SUCCESS'
export const CANDIDATE_SEND_MESSAGE_ERROR = 'CANDIDATE_SEND_MESSAGE_ERROR'

export const CANDIDATE_RECEIVE_MESSAGE = 'CANDIDATE_RECEIVE_MESSAGE'
export const CANDIDATE_RECEIVE_MESSAGE_SUCCESS =
	'CANDIDATE_RECEIVE_MESSAGE_SUCCESS'
export const CANDIDATE_RECEIVE_MESSAGE_ERROR = 'CANDIDATE_RECEIVE_MESSAGE_ERROR'

export const CANDIDATE_CONNECT_USER = 'CANDIDATE_CONNECT_USER'
export const CANDIDATE_CONNECT_USER_SUCCESS = 'CANDIDATE_CONNECT_USER_SUCCESS'
export const CANDIDATE_CONNECT_USER_ERROR = 'CANDIDATE_CONNECT_USER_ERROR'

export const CANDIDATE_FOLLOW_COMPANY = 'CANDIDATE_FOLLOW_COMPANY'
export const CANDIDATE_FOLLOW_COMPANY_SUCCESS =
	'CANDIDATE_FOLLOW_COMPANY_SUCCESS'
export const CANDIDATE_FOLLOW_COMPANY_ERROR = 'CANDIDATE_FOLLOW_COMPANY_ERROR'

export const CANDIDATE_GET_MORE_CONVERSATION = 'CANDIDATE_GET_MORE_CONVERSATION'

//admin social types
export const ADMIN_DASHBOARD_DELETE_POST = 'ADMIN_DASHBOARD_DELETE_POST'
export const ADMIN_DASHBOARD_DELETE_POST_SUCCESS =
	'ADMIN_DASHBOARD_DELETE_POST_SUCCESS'
export const ADMIN_DASHBOARD_DELETE_POST_ERROR =
	'ADMIN_DASHBOARD_DELETE_POST_ERROR'

export const CANDIDATE_GET_MORE_MESSAGES = 'CANDIDATE_GET_MORE_MESSAGES'
